#

pluginName = org.sharedmobility.domainmodel Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_Domain_type = Domain
_UI_Vehilce_type = Vehilce
_UI_Driver_type = Driver
_UI_Passenger_type = Passenger
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_Domain_cars_feature = Cars
_UI_Domain_users_feature = Users
_UI_Domain_drivers_feature = Drivers
_UI_Vehilce_driver_feature = Driver
_UI_Vehilce_passengers_feature = Passengers
_UI_Unknown_feature = Unspecified

_UI_NetworkConnector_type = Network Connector
_UI_NetworkCommunicator_type = Network Communicator
_UI_DirectCommunicator_type = Direct Communicator
_UI_User_type = User
_UI_TraficLight_type = Trafic Light
_UI_SpeedLimit_type = Speed Limit
_UI_RoadsideUnit_type = Roadside Unit
_UI_Participant_type = Participant
_UI_PublicAgency_type = Public Agency
_UI_MobilityServiceProvider_type = Mobility Service Provider
_UI_Address_type = Address
_UI_Credentials_type = Credentials
_UI_BankData_type = Bank Data
_UI_Domain_vehicles_feature = Vehicles
_UI_Domain_participants_feature = Participants
_UI_Domain_publicAgencies_feature = Public Agencies
_UI_Domain_mobilityServiceProvider_feature = Mobility Service Provider
_UI_Domain_roadsideUnits_feature = Roadside Units
_UI_DirectCommunicator_communicationPartmers_feature = Communication Partmers
_UI_TraficLight_state_feature = State
_UI_SpeedLimit_limit_feature = Limit
_UI_Participant_location_feature = Location
_UI_Participant_credentials_feature = Credentials
_UI_Participant_bankData_feature = Bank Data
_UI_MobilityServiceProvider_fleet_feature = Fleet
_UI_TraficLightState_stop_literal = stop
_UI_TraficLightState_go_literal = go
